"""Canonical fixed argument vectors for automated documentation owners."""

import shlex
from dataclasses import dataclass
from typing import Literal

CONTRIBUTOR_JOURNEY_COMMANDS = (
    ("make", "bootstrap"),
    ("make", "pr-check"),
    ("uv", "run", "pytest", "tests/", "-q"),
    ("make", "quality-full"),
    ("make", "docs"),
)
CONTRIBUTOR_JOURNEY_EVIDENCE = " ; ".join(shlex.join(argv) for argv in CONTRIBUTOR_JOURNEY_COMMANDS)

_THREAT_MODEL_COMMAND = (
    "uv",
    "run",
    "pytest",
    "tests/test_threat_model_contract.py",
    "tests/test_ingest_paths.py",
    "tests/test_ingest_prepared.py",
    "tests/test_ingest_prepared_store.py",
    "tests/test_pursuit_effects.py",
    "tests/test_task_effects.py",
    "tests/test_owned_markdown.py",
    "tests/test_text_snapshot.py",
    "tests/test_atomic_text_create.py",
    "tests/test_web_server.py::test_token_guard_rejects_missing_bearer",
    "tests/test_web_server.py::test_tokenless_mode_rejects_foreign_host_header",
    "tests/test_web_server.py::test_tokenless_create_rejects_before_body_validation",
    "tests/test_web_server.py::test_serve_refuses_non_loopback_bind_even_with_token",
    "tests/test_cli_exit.py::test_cli_main_generic_exception_is_exit_3",
    "-q",
    "-n",
    "0",
)

_INTEGRATION_PROFILE_COMMAND = (
    "uv",
    "run",
    "pytest",
    "tests/test_integrations_page_contract.py",
    "tests/test_documentation_integration_profiles.py",
    "tests/test_installation_profiles.py",
    "-q",
    "-n",
    "0",
)

EXAMPLE_COMMANDS: dict[str, tuple[tuple[str, ...], ...]] = {
    "automated.threat-model-contract": (_THREAT_MODEL_COMMAND,),
    "automated.contributor-journey": CONTRIBUTOR_JOURNEY_COMMANDS,
    "automated.contributor-instruction-structure": (
        ("uv", "run", "pytest", "tests/test_documentation_contributor_design.py", "-q", "-n", "0"),
    ),
    "automated.ingest-workflow-scenarios": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_ingest_workflow_scenarios.py",
            "tests/test_gmail_refresh_input_selection.py",
            "tests/test_ingest_approval_effects.py",
            "-q",
            "-n",
            "0",
        ),
    ),
    "automated.remaining-public-scenarios": (
        ("uv", "run", "pytest", "tests/test_remaining_public_skill_contracts.py", "-q", "-n", "0"),
    ),
    "automated.remaining-public-structure": (
        ("uv", "run", "pytest", "tests/test_remaining_public_skill_contracts.py", "-q", "-n", "0"),
    ),
    "automated.brief-workflow-scenarios": (
        ("uv", "run", "pytest", "tests/test_brief_documentation_scenarios.py", "-q", "-n", "0"),
    ),
    "automated.watcher-workflow-scenarios": (
        ("uv", "run", "pytest", "tests/test_watcher_documentation_scenarios.py", "-q", "-n", "0"),
    ),
    "automated.compatibility-policy": (("uv", "run", "python", "scripts/check_compatibility_policy.py"),),
    "automated.configuration-example-contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_documentation_configuration_examples.py",
            "tests/test_config_xdg.py",
            "-q",
            "-n",
            "0",
        ),
    ),
    "automated.contract-workflow-structure-contract": (
        ("uv", "run", "pytest", "tests/test_contract_skill_documentation.py", "-q", "-n", "0"),
    ),
    "automated.documentation-contract": (("uv", "run", "python", "scripts/check_documentation_contract.py"),),
    "automated.draft-review-structure-contract": (
        ("uv", "run", "pytest", "tests/test_draft_review_skill_documentation.py", "-q", "-n", "0"),
    ),
    "automated.exit-code-contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_cli_exit.py",
            "tests/test_documentation_exit_examples.py",
            "-q",
            "-n",
            "0",
        ),
    ),
    "automated.generated-dependency-map": (("uv", "run", "python", "scripts/generate_dep_map.py", "--check"),),
    "automated.generated-reference": (("uv", "run", "python", "scripts/generate_cli_docs.py", "--check"),),
    "automated.gmail-example-contract": (
        ("uv", "run", "pytest", "tests/test_smoke_gmail_examples.py", "-k", "documentation", "-q", "-n", "0"),
    ),
    "automated.gmail-import-scenario": (
        ("uv", "run", "pytest", "tests/test_smoke_gmail_examples.py", "-k", "documentation_import", "-q", "-n", "0"),
    ),
    "automated.handoff-template-contract": (
        ("uv", "run", "pytest", "tests/test_handoff_skill_documentation.py", "-q", "-n", "0"),
    ),
    "automated.humanizer-structure-contract": (
        ("uv", "run", "pytest", "tests/test_humanizer_skill_documentation.py", "-q", "-n", "0"),
    ),
    "automated.installed-base-artifact": (
        ("uv", "run", "python", "scripts/check_documentation_example_scenarios.py", "--json"),
    ),
    "automated.integration-profile-contract": (_INTEGRATION_PROFILE_COMMAND,),
    "automated.meeting-template-contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_tool_routing_cli_first.py",
            "-k",
            "qbr_output_template or meeting_brief_template",
            "-q",
            "-n",
            "0",
        ),
    ),
    "automated.meeting-report-scenarios": (
        ("uv", "run", "pytest", "tests/test_meeting_workflow_scenarios.py", "-q", "-n", "0"),
    ),
    "automated.meeting-report-structure": (
        ("uv", "run", "pytest", "tests/test_meeting_workflow_scenarios.py", "-q", "-n", "0"),
    ),
    "automated.pipeline-example-contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_forecast.py",
            "tests/test_pipeline_quota.py",
            "tests/test_documentation_pursuit_workflow.py",
            "-k",
            "documentation",
            "-q",
            "-n",
            "0",
        ),
    ),
    "automated.release-workflow-policy": (("uv", "run", "python", "scripts/release_workflow_policy.py"),),
    "automated.release-mode-table-contract": (
        ("uv", "run", "pytest", "tests/test_documentation_release_mode_table.py", "-q", "-n", "0"),
    ),
    "automated.security-support-contract": (
        ("uv", "run", "pytest", "tests/test_documentation_security_support.py", "-q", "-n", "0"),
    ),
    "automated.privacy-destination-contract": (
        ("uv", "run", "pytest", "tests/test_documentation_privacy_destinations.py", "-q", "-n", "0"),
    ),
    "automated.roadmap-contract": (("uv", "run", "python", "scripts/check_roadmap_contract.py"),),
    "automated.salesforce-auth-contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_auth_sf.py",
            "tests/test_sf_session_check.py",
            "-k",
            "documentation",
            "-q",
            "-n",
            "0",
        ),
    ),
    "automated.win-loss-template-contract": (
        ("uv", "run", "pytest", "tests/test_win_loss_skill_documentation.py", "-q", "-n", "0"),
    ),
    "automated.workstream-discover-structure-contract": (
        ("uv", "run", "pytest", "tests/test_workstream_discover_skill_documentation.py", "-q", "-n", "0"),
    ),
}

DOCUMENT_COMMANDS: dict[str, tuple[tuple[str, ...], ...]] = {
    "dependency_security_documentation": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_dependency_security_documentation.py",
            "tests/test_check_supply_chain_policy.py",
            "tests/test_runtime_license_inventory.py",
            "tests/test_release_bundle.py::test_materialize_rejects_license_evidence_missing_reconstructible_inputs",
            "tests/test_release_bundle.py::test_materialize_rejects_unbound_runtime_license_inputs",
            "tests/test_release_bundle.py::test_materialize_rejects_self_hashed_observations_disagreeing_with_receipt",
            "tests/test_release_bundle.py::test_verify_rejects_rechecksummed_license_input_swap",
            "tests/test_release_bundle.py::test_materialize_rejects_receipt_rows_and_markers_disagreeing_with_raw_inventory",
            "-q",
            "-n",
            "0",
        ),
    ),
    "threat_model_contract": (_THREAT_MODEL_COMMAND,),
    "shadowbot_auth_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_shadowbot_auth_guide_contract.py",
            "tests/test_auth_shadowbot.py",
            "tests/test_protected_input.py",
            "tests/test_doctor.py::test_check_shadowbot_no_token_file_not_configured",
            "tests/test_doctor.py::test_check_shadowbot_live_token_resolves_healthy",
            "tests/test_doctor.py::test_check_shadowbot_auth_error_unhealthy",
            "tests/test_doctor.py::test_doctor_shadowbot_cmd_exits_two_when_not_configured",
            "-q",
            "-n",
            "0",
        ),
    ),
    "ingest_agent_instruction_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_domain_agent_instruction_contract.py",
            "tests/test_ingest_db.py",
            "tests/test_ingest_prepared_store.py",
            "tests/test_ingest_run_lock.py",
            "tests/test_gmail_discover.py",
            "tests/test_ingest_sources.py",
            "tests/test_ingest_run_branches.py::test_run_rejects_unverified_gmail_before_registry_mutation",
            "tests/test_ingest_docs.py::test_fetch_gemini_doc_transcript_tab_title_renamed_falls_back_to_index",
            "tests/test_transcript_pipeline.py",
            "tests/test_ingest_reprocess_branches.py",
            "-q",
            "-n",
            "0",
        ),
    ),
    "pursuit_agent_instruction_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_pursuit_agent_instruction_contract.py",
            "tests/test_pursuit_validation.py",
            "tests/test_pursuit_io.py",
            "tests/test_pursuit_io_render_and_write_raw.py",
            "tests/test_pursuit_body_update.py",
            "tests/test_pursuit_stages.py",
            "tests/test_pursuit_affiliations.py",
            "tests/test_pursuit_monetary.py",
            "tests/test_cli_exit.py::test_cli_main_frontmatter_staleness_error_is_exit_1",
            "-q",
            "-n",
            "0",
        ),
    ),
    "watch_agent_instruction_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_watch_agent_instruction_contract.py",
            "tests/test_watch_state.py",
            "tests/test_watch_status_cmd.py",
            "tests/test_watcher_status.py",
            "tests/watch/test_alert_dedup.py",
            "tests/test_pursuit_stalls_stage_change.py",
            "tests/test_watch_backstory_health.py::test_run_backstory_health_dry_run_does_not_read_accounts_or_provider",
            "tests/test_watch_backstory_health.py::test_state_write_failure_is_fatal",
            "-q",
            "-n",
            "0",
        ),
    ),
    "gmail_command_readme_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_gmail_command_readme_contract.py",
            "tests/test_installation_profiles.py",
            "-q",
            "-n",
            "0",
        ),
    ),
    "adr_architecture_contract": (("uv", "run", "pytest", "tests/test_adr_architecture_claims.py", "-q", "-n", "0"),),
    "adr_persistence_release_contract": (
        ("uv", "run", "pytest", "tests/test_adr_persistence_release_claims.py", "-q", "-n", "0"),
    ),
    "public_concepts_design_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_public_concepts_design_claims.py",
            "tests/test_documentation_contributor_design.py",
            "-q",
            "-n",
            "0",
        ),
    ),
    "overview_page_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_overview_page_contract.py",
            "tests/test_documentation_integration_profiles.py",
            "tests/test_documentation_pursuit_workflow.py",
            "tests/test_brief_documentation_scenarios.py::test_documented_morning_brief_previews_are_offline_and_read_only",
            "-q",
            "-n",
            "0",
        ),
    ),
    "integrations_page_contract": (_INTEGRATION_PROFILE_COMMAND,),
    "contributor_patterns_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_contributor_patterns_page_contract.py",
            "tests/test_ingest_prepared_store.py::test_replay_failure_retains_intent",
            "tests/test_ingest_run_lock.py::test_busy_run_has_no_database_or_discovery_effects",
            "tests/test_owned_markdown.py::test_non_owned_examples_are_excluded",
            "tests/test_text_snapshot.py::test_snapshot_refuses_change_during_read",
            "tests/test_atomic_text_create.py::test_atomic_create_refuses_existing_destination",
            "-q",
            "-n",
            "0",
        ),
    ),
    "privacy_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_privacy_guide_contract.py",
            "tests/test_documentation_privacy_destinations.py",
            "tests/test_protected_input.py",
            "tests/test_sqlite_read_only.py",
            "tests/test_sqlite_snapshot_worker.py",
            "tests/test_config_xdg.py::test_config_and_cookie_paths_follow_absolute_xdg_root",
            "tests/test_config_xdg.py::test_relative_xdg_root_falls_back_to_home_config",
            "tests/test_init_guide_contract.py::test_real_minimal_init_and_preserving_rerun",
            "tests/test_ingest_prepared.py::test_prepared_output_round_trip_preserves_classified_tasks",
            "tests/test_ingest_prepared.py::test_prepared_path_rejects_symlink_escape",
            "tests/test_ingest_prepared.py::test_prepared_tasks_refuse_symlink_redirection",
            "tests/test_ingest_prepared_store.py::test_save_is_durable_and_identical_retry_does_not_write",
            "tests/test_ingest_prepared_store.py::test_completion_commits_artifact_status_and_checkpoint_together",
            "tests/test_ingest_prepared_store.py::test_completion_failure_retains_checkpoint_and_claim",
            "tests/test_reprocess_journal.py::test_reprocess_journal_commits_exact_intent",
            "tests/test_reprocess_journal.py::test_prepare_reprocess_saves_before_publication",
            "tests/test_reprocess_journal.py::test_reprocess_replay_applies_then_completes",
            "tests/test_reprocess_journal.py::test_reprocess_replay_refuses_changed_state",
            "tests/test_reprocess_journal.py::test_reprocess_completion_rolls_back_when_journal_delete_fails",
            "tests/test_reprocess_journal.py::test_reprocess_journal_refuses_descendant_alias",
            "tests/test_owned_markdown.py",
            "tests/test_ingest_db.py::test_get_db_path_falls_back_to_fieldkit_data_when_override_absent",
            "tests/test_ingest_db.py::test_get_db_path_rejects_override_outside_approved_roots",
            "-q",
            "-n",
            "0",
        ),
    ),
    "troubleshooting_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_troubleshooting_guide_contract.py",
            "tests/test_documentation_exit_examples.py::test_troubleshooting_table_matches_runtime_and_recovery",
            "tests/test_doctor.py::test_gmail_doctor_diagnostics_do_not_expose_selected_paths",
            "tests/test_doctor.py::test_gmail_data_failures_are_non_destructive_data_errors",
            "tests/test_sf_session_check.py::test_documentation_session_transcripts",
            "tests/test_sf_session_check.py::test_session_diagnostics_are_payload_free",
            "tests/test_watch_cli_logs.py",
            "tests/test_brief_workspace_required.py",
            "tests/test_ingest_run_lock.py::test_busy_run_has_no_database_or_discovery_effects",
            "tests/test_ingest_prepared_store.py::test_command_recovers_real_interrupted_state_only_under_lock",
            "tests/test_ingest_prepared_store.py::test_source_processor_replays_before_fetching",
            "tests/test_ingest_prepared_store.py::test_resumed_source_hides_private_replay_failure",
            "tests/test_ingest_prepared_store.py::test_replay_missing_pursuit_then_repair_preserves_note_edits",
            "tests/test_ingest_prepared_store.py::test_replay_failure_retains_intent",
            "tests/test_pursuit_effects.py::test_activity_requires_legacy_reconciliation",
            "tests/test_pursuit_effects.py::test_activity_rejects_ambiguous_marker",
            "tests/test_task_effects.py::test_ambiguous_markers_fail_closed",
            "tests/test_cli_exit.py::test_missing_optional_dependency_is_actionable_without_traceback",
            "-q",
            "-n",
            "0",
        ),
    ),
    "init_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_init_guide_contract.py",
            "tests/test_init_config_preservation.py",
            "tests/test_init_config_merge.py",
            "tests/test_init_wizard_funcs.py::test_load_answers_returns_typed_values_and_defaults",
            "tests/test_init_wizard_funcs.py::test_load_answers_rejects_invalid_document",
            "tests/test_init_wizard_funcs.py::test_account_key_normalizes_safe_name_and_rejects_traversal",
            "tests/test_init_wizard_extended.py::test_write_env_temp_is_restricted_before_publication",
            "tests/test_init_wizard_extended.py::test_write_env_preserves_exact_dotenv_values",
            "tests/test_init_wizard_extended.py::test_write_env_rejects_symlink_without_changing_target",
            "tests/test_init_wizard_run_wizard_orchestration.py::test_confirm_true_writes_then_post_setup_and_returns_0",
            "tests/test_init_wizard_run_wizard_orchestration.py::test_confirm_false_returns_0_without_write_or_post_setup",
            "tests/test_init_wizard_run_wizard_orchestration.py::test_answers_mode_does_not_start_an_interactive_skill_install",
            "tests/test_init_wizard_extended.py::test_wizard_post_setup_handles_skill_install_failure",
            "tests/test_skill_runner_dispatch.py::test_skills_dir_importlib_resources_failure_is_fixed_config_error",
            "tests/test_skill_runner_dispatch.py::test_skills_dir_rejects_non_directory_bundled_resource",
            "-q",
            "-n",
            "0",
        ),
    ),
    "pipeline_workflow_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_pipeline_workflow_guide_contract.py",
            "tests/test_documentation_pursuit_workflow.py::test_documentation_sync_account_scope_matches_selected_steps",
            "tests/test_documentation_pursuit_workflow.py::test_documentation_sync_forwards_account_to_in_process_people_index",
            "tests/test_sync.py::test_cli_dry_run_never_preflights_credentials",
            "tests/test_sync.py::test_selected_sync_preflight_failure_maps_to_auth_exit_two",
            "tests/test_sync.py::test_cli_json_reports_optional_inputs_that_were_not_run",
            "tests/test_sync_verbose.py::test_truncate_output_truncation_keeps_tail_not_head",
            "tests/test_sync_verbose.py::test_verbose_help_discloses_output_limit",
            "tests/test_sync_verbose.py::test_truncate_output_single_line_respects_character_cap",
            "tests/test_ingest_run_lock.py::test_busy_run_has_no_database_or_discovery_effects",
            "tests/test_ingest_prepared_store.py::test_new_source_commits_intent_before_output",
            "tests/test_ingest_prepared_store.py::test_replay_batch_needs_no_google_credentials",
            "tests/test_ingest_prepared_store.py::test_command_recovers_real_interrupted_state_only_under_lock",
            "tests/test_ingest_prepared_store.py::test_replay_failure_retains_intent",
            "tests/test_ingest_prepared_store.py::test_replay_missing_pursuit_then_repair_preserves_note_edits",
            "tests/test_ingest_prepared.py::test_prepared_task_replay_preserves_original_positions_and_edits",
            "tests/test_pursuit_effects.py::test_activity_rejects_ambiguous_marker",
            "tests/test_ingest_promote_extended.py::test_auto_task_then_promotion_skips_mine_and_continues_waiting",
            "tests/test_reprocess_journal.py::test_reprocess_command_recovers_without_credentials",
            "tests/test_reprocess_journal.py::test_reprocess_excluded_recovery_blocks_fresh_work",
            "tests/test_reprocess_journal.py::test_new_recovery_stops_before_second_fresh_artifact",
            "tests/test_reprocess_journal.py::test_reprocess_command_recovers_recorded_version_without_repreparing",
            "tests/test_reprocess_journal.py::test_reprocess_replay_refuses_changed_state",
            "tests/test_ingest_ambient.py::test_discover_cli_dry_run_hides_transcript_text_and_excludes_latest",
            "tests/test_ingest_ambient.py::test_discovery_include_latest_reads_all_stable_sessions",
            "tests/test_ingest_ambient.py::test_process_ambiguous_route_defers_and_restores_pending",
            "tests/test_ingest_ambient.py::test_run_cli_reports_noise_as_successful_skip",
            "tests/test_documentation_pursuit_workflow.py::test_documentation_audit_output_and_default_report",
            "tests/test_pursuit_audit_cmd.py::test_cli_no_results_exits_3",
            "tests/test_pursuit_audit_cmd.py::test_write_audit_report_json_flag_suppresses_report_write",
            "tests/test_pursuit_legacy_meddpicc.py::test_former_meddpicc_loads_as_typed_historical_data_without_mutating_file",
            "tests/test_pursuit_legacy_meddpicc.py::test_authorized_model_write_canonicalizes_in_place_and_preserves_content",
            "tests/test_pursuit_audit.py::test_audit_file_missing_stage",
            "tests/test_pursuit_audit.py::test_audit_file_overdue_close_date",
            "tests/test_pursuit_audit.py::test_audit_file_backstory_in_frontmatter",
            "tests/test_pursuit_audit.py::test_audit_file_backstory_in_body",
            "tests/test_pursuit_audit.py::test_audit_file_invalid_gate_result_in_history_produces_warning",
            "tests/test_pursuit_audit.py::test_apply_fixes_renames_hyphenated",
            "tests/test_pursuit_audit_cmd.py::test_cli_check_yaml_with_dups_exits_1",
            "tests/test_pursuit_audit_cmd.py::test_cli_output_path_respected",
            "tests/test_documentation_pursuit_workflow.py::test_documentation_advance_preview_is_pending_without_writes",
            "tests/test_pursuit_advance_branches.py::test_advance_cmd_override_advances_despite_failure",
            "tests/test_pursuit_advance_branches.py::test_apply_transition_appends_history_entry",
            "tests/test_forecast.py::test_documentation_forecast_example_matches_implemented_scenarios",
            "tests/test_sf_components.py::test_effective_net_consulting_acv",
            "tests/test_contract_type_acv_anchor.py::test_forecast_fixed_price_anchors_on_net_acv",
            "tests/test_pipeline_quota.py::test_documentation_local_quota_output_matches_cli",
            "tests/test_quota_period.py::test_quota_period_end_date_matches_calendar",
            "tests/test_pipeline_quota.py::test_quota_cli_source_sf_shows_territory_scoped_gap",
            "tests/test_pipeline_sf_sync_documentation.py::test_documented_listview_json_format_does_not_choose_write_authority",
            "tests/test_pipeline_sf_sync_documentation.py::test_documented_sf_provider_failures_remain_nonpassing_and_never_write",
            "tests/test_pipeline_cli.py::test_pipeline_open_account_selects_only_newest_matching_review",
            "tests/test_pipeline_cli.py::test_pipeline_open_global_ignores_newer_scoped_review",
            "tests/test_pipeline_cli.py::test_pipeline_open_missing_account_review_fails_without_fallback",
            "tests/test_pipeline_cli.py::test_pipeline_open_without_account_fails_when_only_scoped_review_exists",
            "tests/test_sf_quote.py::test_actual_cli_quote_failures_are_sanitized",
            "tests/test_sf_quote.py::test_actual_cli_successfully_empty_quote_lines",
            "tests/test_sf_quote.py::test_actual_cli_missing_quote_configuration",
            "tests/test_sf_quote.py::test_fetch_quote_lines_parses_related_list_records",
            "tests/test_sf_quote.py::test_build_payload_header_fields_mapped",
            "tests/test_sf_meddpicc.py::test_cli_passes_exact_deal_id_to_native_reader",
            "tests/test_sf_meddpicc.py::test_cli_json_reports_ambiguity_with_all_deal_ids_and_exits_partial",
            "tests/test_sf_meddpicc.py::test_cli_json_reports_incomplete_result_and_exits_partial",
            "tests/test_sf_meddpicc.py::test_cli_json_preserves_named_party_evidence_and_zero_state",
            "tests/test_sf_meddpicc.py::test_cli_json_no_closeplan_returns_empty_normalized_collections",
            "tests/test_sf_meddpicc.py::test_cli_exits_3_for_invalid_opp_id",
            "tests/test_sf_meddpicc.py::test_cli_exits_2_when_auth_error_raised",
            "tests/test_sf_meddpicc_domain.py::test_normalize_questions_distinguishes_population_states",
            "tests/test_sf_meddpicc_domain.py::test_normalize_questions_retains_unknown_and_missing_categories",
            "tests/test_sf_meddpicc_domain.py::test_normalize_question_preserves_exact_identity_raw_fields_and_concurrency",
            "tests/test_sf_meddpicc_domain.py::test_normalize_field_metadata_keeps_only_proven_generic_describe_properties",
            "tests/test_sf_meddpicc_domain.py::test_normalize_questions_keeps_duplicate_presentation_text_as_exact_records",
            "tests/test_sf_meddpicc_template_metadata.py::test_fetch_meddpicc_scorecard_preserves_mode_version_and_native_maximum_consistency",
            "tests/test_sf_meddpicc_template_metadata.py::test_fetch_meddpicc_scorecard_rejects_template_question_ownership_drift",
            "tests/test_sf_meddpicc_template_metadata.py::test_fetch_meddpicc_scorecard_rejects_native_maximum_total_drift",
            "tests/test_sf_meddpicc_template_metadata.py::test_fetch_meddpicc_scorecard_keeps_non_answers_mode_readable_but_mutation_disabled",
            "tests/test_sf_meddpicc_template_metadata.py::test_fetch_meddpicc_scorecard_deduplicates_template_reads_and_preserves_exact_choices",
            "tests/test_sf_meddpicc_template_metadata.py::test_fetch_meddpicc_scorecard_propagates_incomplete_template_answer_count",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_deals_returns_every_record_with_complete_count_evidence",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_deals_marks_count_mismatch_incomplete",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_deals_marks_missing_count_incomplete",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_questions_returns_all_records_with_complete_count_evidence",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_template_answers_reads_exact_choices_with_complete_count_evidence",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_template_answers_404_is_incomplete_not_empty",
            "-q",
            "-n",
            "0",
        ),
    ),
    "morning_brief_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_morning_brief_guide_contract.py",
            "tests/test_brief_documentation_scenarios.py",
            "tests/test_brief_optional_integrations.py",
            "tests/test_brief_workspace_required.py",
            "tests/test_brief_account_scope.py",
            "tests/test_saved_report_viewers.py",
            "tests/test_brief_cli_open.py",
            "tests/test_morning_brief_inner.py::test_run_generate_inner_dry_run_overrides_selected_llm",
            "tests/test_morning_brief_inner.py::test_preview_retains_actual_source_failure_outcome_without_writes",
            "tests/test_morning_brief_inner.py::test_run_generate_inner_labels_unconfigured_optional_alert_inputs",
            "tests/test_morning_brief_write_result.py::test_calendar_auth_preserves_report_and_propagates_through_generator",
            "tests/test_morning_brief_write_result.py::test_pipeline_user_action_errors_propagate_without_publication",
            "tests/test_morning_brief_write_result.py::test_written_artifact_retains_source_failure_status",
            "tests/test_morning_brief_write_result.py::test_generator_json_reports_actual_publication_on_partial_exit",
            "tests/test_morning_brief.py::test_calendar_not_configured_is_explicitly_not_run",
            "tests/test_morning_brief.py::test_collect_tasks_reads_from_data_root",
            "tests/test_morning_brief.py::test_collect_tasks_does_not_read_from_fieldkit_root",
            "tests/test_morning_brief_collect.py::test_collect_decay_signals_returns_sentinel_when_no_gmail_db",
            "-q",
            "-n",
            "0",
        ),
    ),
    "watcher_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_watcher_guide_contract.py",
            "tests/test_watch_aggregate_result_contract.py",
            "tests/test_watcher_documentation_scenarios.py",
            "tests/test_optional_integration_plan.py::test_base_plan_selects_only_local_work",
            "tests/test_optional_integration_plan.py::test_selected_services_and_watchers_have_one_ordered_plan",
            "tests/test_optional_integration_plan.py::test_disabled_llm_wins_over_configured_model",
            "tests/test_watch_backstory_health.py::test_run_backstory_health_dry_run_does_not_read_accounts_or_provider",
            "tests/test_watch_backstory_health.py::test_compute_health_score_rejects_invalid_numeric_values",
            "tests/test_watch_backstory_health.py::test_check_account_missing_scorable_opportunities_records_failure_without_alert_or_state",
            "tests/test_watch_backstory_health.py::test_check_account_rejects_malformed_provider_shape",
            "tests/test_watch_backstory_health.py::test_malformed_backstory_result_preserves_existing_state_without_write",
            "tests/test_watch_backstory_health.py::test_scan_result_reports_total_fatal_or_completed_partial",
            "tests/test_watch_slack_threads.py::test_decoded_search_envelope_fails_closed",
            "tests/test_watch_slack_threads.py::test_valid_zero_match_envelope_is_success",
            "tests/test_watch_slack_threads.py::test_successful_producer_zero_match_empty_stdout_is_success",
            "tests/test_watch_slack_threads.py::test_unsuccessful_empty_stdout_cannot_manufacture_zero_match_success",
            "tests/test_watch_slack_threads.py::test_decoded_provider_error_is_incomplete_at_domain_and_real_cli",
            "tests/test_draft_queue.py::test_scoped_draft_scan_preserves_global_snapshot",
            "tests/test_draft_queue.py::test_run_counts_only_published_draft_alerts",
            "tests/test_watcher_status.py::test_classify_watcher_outcome_preserves_partial_failures",
            "-q",
            "-n",
            "0",
        ),
    ),
    "sf_agent_instruction_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_sf_agent_instruction_contract.py",
            "tests/test_sf_reauth_hint.py::test_sf_errors_import_without_transport_or_client",
            "tests/test_sf_reauth_hint.py::test_sf_errors_have_no_old_client_or_package_aliases",
            "tests/test_sf_reauth_hint.py::test_sf_private_helpers_have_no_old_client_aliases",
            "tests/test_sf_reauth_hint.py::test_sf_schema_diagnostics_do_not_reflect_private_inputs",
            "tests/test_pipeline_sf_sync_documentation.py::test_documented_sf_provider_failures_remain_nonpassing_and_never_write",
            "tests/test_sf_direct.py::test_fetch_record_fetch_record_uses_sobjects_path",
            "tests/test_sf_direct.py::test_fetch_record_fetch_record_cookie_header",
            "tests/test_sf_direct.py::test_search_opportunities_search_opportunities_uses_name_fields_scope",
            "tests/test_sf_direct.py::test_search_opportunities_search_opportunities_sosl_includes_services_filter",
            "tests/test_sf_direct.py::test_search_opportunities_search_opportunities_empty_results",
            "tests/test_sf_direct.py::test_resolve_account_id_by_keywords_resolve_account_id_uses_name_fields_scope",
            "tests/test_sf_direct.py::test_fetch_sobject_errors_raise_public_exception_with_message",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_deals_marks_count_mismatch_incomplete",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_deals_marks_missing_count_incomplete",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_deals_404_returns_complete_empty_collection",
            "tests/test_sf_client_closeplan.py::test_fetch_closeplan_template_answers_404_is_incomplete_not_empty",
            "tests/test_sf_session_check.py::test_probe_uses_canonical_api_version",
            "tests/test_sf_session_check.py::test_bearer_auth_regression_uses_bearer_auth_header",
            "tests/test_sf_retry_classification.py::test_401_is_never_retried",
            "tests/test_cli_exit.py::test_handle_cli_exception_sfautherror_routes_via_autherror_base",
            "tests/test_auth_sf.py::test_write_sid_cookie_file_permissions_are_600",
            "tests/test_config_xdg.py::test_config_and_cookie_paths_follow_absolute_xdg_root",
            "-q",
            "-n",
            "0",
        ),
    ),
    "llm_agent_instruction_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_llm_agent_instruction_contract.py",
            "tests/test_llm.py",
            "tests/test_llm_core.py",
            "tests/test_llm_lazy_model.py",
            "tests/test_llm_env_aliases.py",
            "tests/test_transcribe.py",
            "tests/test_report_llm_contract.py",
            "tests/test_cli_exit.py::test_cli_main_llm_auth_error_is_exit_2",
            "tests/test_cli_exit.py::test_cli_main_llm_rate_limit_is_exit_1",
            "tests/test_cli_exit.py::test_cli_main_llm_general_error_is_exit_3",
            "tests/test_cli_exit.py::test_cli_main_transcribe_error_is_exit_3",
            "tests/test_documentation_configuration_examples.py::test_environment_reference_no_llm_values",
            "tests/test_documentation_configuration_examples.py::test_environment_reference_no_llm_skips_providers",
            "tests/test_documentation_configuration_examples.py::test_environment_reference_transcription_precedence",
            "-q",
            "-n",
            "0",
        ),
    ),
    "configuration_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_configuration_document_owner.py",
            "tests/test_documentation_configuration_examples.py",
            "tests/test_config_xdg.py",
            "tests/test_companion_exact_permissions.py",
            "tests/test_companion_read_permissions.py",
            "tests/test_saved_report_viewers.py",
            "tests/test_driver_prompt_contract.py::test_freeze_prompt_reads_contract_and_target_from_same_revision",
            "tests/test_driver_prompt_contract.py::test_validate_edit_sites_rejects_unknown_or_ambiguous_anchor",
            "tests/test_driver_prompt_contract.py::test_freeze_openspec_requires_revision_bound_sidecar",
            "tests/test_driver.py::test_create_worktree_adds_from_frozen_revision",
            "tests/test_ingest_sync_action_items.py::test_classification_stops_before_classifier_on_invalid_accounts_file",
            "tests/test_ingest_sync_action_items.py::test_classification_rejects_malformed_account_ownership",
            "tests/test_ingest_sync_action_items.py::test_invalid_attendee_metadata_is_rejected",
            "tests/test_config_workspace_accounts.py::test_account_collector_binds_strict_read_to_its_workspace",
            "tests/test_config_workspace_accounts.py::test_pipeline_invalid_selected_accounts_stops_before_report_publication",
            "tests/test_config_workspace_accounts.py::test_account_collectors_propagate_invalid_selected_config",
            "tests/test_companion_gate.py::test_allowed_and_run_apply_same_tier_allowlist_policy",
            "tests/test_companion_runner.py::test_run_action_permitted_executes_and_journals",
            "tests/test_shadowbot_config.py::test_get_shadowbot_api_base_rejects_unsafe_destination",
            "tests/test_pipeline_quota.py::test_fetch_sf_closed_won_raises_auth_error_on_no_sid",
            "tests/test_pipeline_quota.py::test_selected_workspace_controls_resolution_write_and_query",
            "tests/test_pipeline_quota.py::test_quota_cli_source_sf_shows_territory_scoped_gap",
            "tests/test_skill_runner_dispatch.py::test_skills_dir_rejects_invalid_configured_root",
            "tests/test_skill_runner_dispatch.py::test_skills_dir_config_root_prefers_agents_skills_over_bare_skills",
            "tests/test_skill_runner_dispatch.py::test_skills_dir_importlib_resources_failure_is_fixed_config_error",
            "tests/test_config_source.py",
            "tests/test_init_wizard_funcs.py::test_minimal_cli_creates_only_generic_offline_scaffolding",
            "tests/test_configuration_reference_claims.py",
            "tests/test_forecast.py::test_forecast_auto_quota_auto_quota_from_config",
            "tests/test_driver_batch.py::test_batch_of_two_disjoint_issues_both_execute",
            "tests/test_driver_batch.py::test_batch_overlapping_second_issue_skipped_with_reason",
            "tests/test_contact_resolver.py::test_self_email_falls_back_to_configured_name",
            "tests/test_contact_resolver.py::test_self_email_case_insensitive_match",
            "tests/test_contact_enrich_pipeline.py::test_exclusion_guard_skip_user_own_email",
            "tests/test_contact_enrich_pipeline.py::test_enrich_batch_user_identity_contact_is_excluded",
            "tests/test_lib_config.py::test_get_user_name_returns_name_from_config",
            "tests/test_draft_queue.py::test_run_draft_queue_missing_endpoint_is_invalid_configuration",
            "tests/test_draft_queue.py::test_run_draft_queue_dry_run_returns_exit_0_no_mcp",
            "tests/test_watch_backstory_health.py::test_run_backstory_health_dry_run_does_not_read_accounts_or_provider",
            "tests/test_morning_brief.py::test_calendar_not_configured_is_explicitly_not_run",
            "tests/test_config_backward_compat.py::test_missing_canonical_workspace_key_raises_config_error",
            "tests/test_mcp_integration_config.py",
            "tests/test_watch_backstory_health.py::test_missing_backstory_endpoint_is_invalid_configuration",
            "tests/test_quota_period.py",
            "tests/test_driver.py::test_run_driver_limits_capped_execution_to_one_admitted_issue",
            "tests/test_dotenv_compat.py::test_load_dotenv_safe_preserves_existing_environment_by_default",
            "tests/test_gmail_sync.py::test_cached_token_needs_no_separate_client_settings",
            "tests/test_driver_admission.py::test_admit_fails_closed_when_run_budget_is_unset",
            "tests/test_driver_admission.py::test_admit_rejects_unreadable_or_exhausted_spend",
            "-q",
            "-n",
            "0",
        ),
    ),
    "first_user_guides_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_first_user_guides_contract.py",
            "tests/test_init_guide_contract.py::test_real_minimal_init_and_preserving_rerun",
            "tests/test_init_guide_contract.py::test_real_minimal_workspace_discovers_bundled_workflows",
            "tests/test_init_guide_contract.py::test_real_invalid_answers_leave_every_file_unchanged",
            "tests/test_installation_profiles.py::test_base_profile_supports_offline_first_success",
            "tests/test_installation_profiles.py::test_base_doctor_accepts_unconfigured_integrations",
            "tests/test_installation_profiles.py::test_base_doctor_preserves_auth_failure_for_enabled_integration",
            "tests/test_installation_profiles.py::test_base_doctor_reports_missing_explicit_google_token_as_auth_required",
            "tests/test_installation_profiles.py::test_base_doctor_rejects_incomplete_shadowbot_configuration",
            "tests/test_installation_profiles.py::test_profile_success_surface",
            "tests/test_installation_profiles.py::test_base_profile_reports_actionable_missing_profile",
            "tests/test_doctor.py::test_doctor_bare_all_healthy_exits_zero",
            "tests/test_doctor.py::test_aggregate_doctor_preserves_failure_priority",
            "tests/test_smoke_artifact.py::test_first_use_doctor_requires_all_services_disabled_and_clean_stderr",
            "tests/test_smoke_artifact.py::test_first_use_skill_list_requires_known_packaged_skills_and_clean_stderr",
            "tests/test_smoke_artifact.py::test_getting_started_trial_is_ordered_isolated_and_resolves_trial_roots",
            "tests/test_smoke_artifact.py::test_trial_recipe_binding_rejects_changes",
            "tests/test_smoke_artifact.py::test_isolated_trial_clears_external_skill_selector_in_recipe_and_runner",
            "tests/test_smoke_artifact.py::test_published_first_use_sequences_are_ordered_and_share_only_their_own_roots",
            "tests/test_smoke_artifact.py::test_smoke_records_exact_digest_environment_and_all_contracts",
            "tests/test_smoke_artifact.py::test_all_profile_installs_exact_artifact_extra_and_exercises_each_integration",
            "tests/test_smoke_artifact.py::test_uv_installer_targets_the_exact_artifact_and_created_environment",
            "tests/test_check_documentation_example_scenarios.py::test_check_binds_each_safe_documentation_block_to_fixed_smoke_criteria",
            "tests/test_check_documentation_example_scenarios.py::test_check_fails_when_a_documented_command_criterion_is_missing",
            "tests/test_check_documentation_example_scenarios.py::test_check_rejects_failed_artifact_even_when_mapped_examples_pass",
            "tests/test_pursuit_create.py::test_create_cmd_creates_pursuit_file",
            "tests/test_pursuit_create.py::test_create_cmd_json_dry_run_does_not_write",
            "tests/test_pipeline_workflow_guide_contract.py::test_real_audit_json_has_unavailable_qualification_and_no_writes",
            "tests/test_pipeline_workflow_guide_contract.py::test_real_advance_pending_then_explicit_override_preserves_historical_data",
            "tests/test_pipeline_workflow_guide_contract.py::test_real_forecast_scopes_account_preserves_acv_precedence_and_overrides_quota",
            "tests/test_optional_integration_plan.py::test_base_plan_selects_only_local_work",
            "tests/test_brief_documentation_scenarios.py::test_documented_morning_brief_previews_are_offline_and_read_only",
            "tests/test_pipeline_sf_sync_documentation.py::test_documented_listview_json_format_does_not_choose_write_authority",
            "tests/test_gmail_published_sync.py::test_complete_provider_page_publishes_rows_and_checkpoint_together",
            "tests/test_documentation_integration_profiles.py::test_integration_profile_table_matches_installation_and_import_contract",
            "tests/test_documentation_integration_profiles.py::test_google_library_installation_does_not_supply_oauth_credentials",
            "tests/test_check_dependency_profiles.py::test_live_dependency_profile_contract_passes",
            "tests/test_check_compatibility_policy.py::test_live_compatibility_contract_passes",
            "tests/test_quality_contract.py::test_public_contributor_targets_use_locked_environment_and_canonical_gate",
            "tests/test_pursuit_create.py::test_create_cmd_exits_nonzero_missing_account_dir",
            "tests/test_watcher_guide_contract.py::test_real_unconfigured_aggregate_runs_four_locals_and_nonempty_no_llm_brief",
            "tests/test_pipeline_workflow_guide_contract.py::test_real_pipeline_generation_and_open_use_the_same_scope_without_a_viewer",
            "tests/test_documentation_pursuit_workflow.py::test_documentation_audit_output_and_default_report",
            "-q",
            "-n",
            "0",
        ),
    ),
    "sf_auth_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_sf_auth_guide_contract.py",
            "tests/test_auth_sf.py::test_authentication_rolls_back_every_unsuccessful_validation",
            "tests/test_auth_sf.py::test_reauthentication_refuses_unsafe_existing_file",
            "tests/test_auth_sf.py::test_reauthentication_replaces_ambiguous_or_lookalike_sessions",
            "tests/test_auth_sf.py::test_documentation_suspicious_sid_warning",
            "tests/test_auth_sf.py::test_documentation_interactive_auth_success_transcript",
            "tests/test_auth_sf.py::test_invalid_credential_does_not_create_parent",
            "tests/test_auth_sf.py::test_write_sid_cookie_recovers_malformed_json",
            "tests/test_auth_sf.py::test_write_sid_cookie_preserves_other_cookies",
            "tests/test_sf_session_check.py::test_documentation_session_transcripts",
            "tests/test_sf_session_check.py::test_session_diagnostics_are_payload_free",
            "tests/test_sf_session_check.py::test_unsafe_cookie_input_never_sends_credentials",
            "tests/test_sf_session_check.py::test_network_error_retry_exhausted",
            "tests/test_sf_session_check.py::test_bearer_auth_regression_uses_bearer_auth_header",
            "tests/test_sf_session_check.py::test_probe_hits_account_describe_endpoint",
            "tests/test_sf_session_check.py::test_mixed_valid_and_lookalike_sid_selects_only_valid_cookie",
            "-q",
            "-n",
            "0",
        ),
    ),
    "gmail_guide_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_gmail_guide_contract.py",
            "tests/test_gmail_sync_selected_mode.py",
            "tests/test_smoke_gmail_examples.py::test_documentation_account_tag_transcript",
            "tests/test_gmail_enrich_pursuits_json.py::test_json_reports_written_and_skipped_accounts",
            "tests/test_gmail_query_cli_commands.py::test_cmd_blindspots_json_preserves_suspect_without_consuming_limit",
            "tests/test_smoke_gmail_examples.py::test_documentation_gmail_doctor_retries_until_published_cache_is_query_ready",
            "tests/test_smoke_gmail_examples.py::test_documentation_import_executes_fixed_legacy_cache_example",
            "tests/test_smoke_gmail_examples.py::test_documentation_import_rejects_occupied_destination_without_writes",
            "tests/test_smoke_gmail_examples.py::test_documentation_import_cli_rejects_copied_managed_source",
            "tests/test_gmail_cache_import.py::test_preview_rejects_unknown_schema_without_creating_a_target",
            "tests/test_gmail_sync_coverage.py::test_negative_max_messages_exits_three_before_auth_or_db",
            "tests/test_gmail_refresh_input_selection.py::test_import_to_different_target_preserves_selection_for_doctor_tags_and_enrichment",
            "tests/test_gmail_refresh_input_selection.py::test_valid_account_without_pursuits_skips_without_creating_or_replacing_report",
            "tests/test_enrich_pursuits.py::test_build_account_report_no_db_build_account_report_calls_direct_functions",
            "tests/test_enrich_pursuits.py::test_review_checklist_routes_email_evidence_to_read_only_native_coaching",
            "tests/test_enrich_pursuits.py::test_build_account_report_sets_aside_suspected_masked_contacts",
            "tests/test_gmail_query_cli_commands.py::test_cmd_blindspots_sets_aside_suspected_masked_address_by_default",
            "tests/test_gmail_query_cli_commands.py::test_cmd_blindspots_include_suspected_marks_address",
            "tests/test_gmail_query_cli_commands.py::test_cmd_blindspots_missing_domains_preserves_matching_shape",
            "tests/test_gmail_address_quality.py::test_is_suspected_masked_address",
            "-q",
            "-n",
            "0",
        ),
    ),
    "driver_executor_contract": (
        (
            "uv",
            "run",
            "pytest",
            "tests/test_driver_executor_documentation.py",
            "tests/test_driver_prompt_contract.py",
            "tests/test_driver_opencode.py",
            "tests/test_driver_change_authority.py",
            "tests/test_driver_done_check_executor.py",
            "-q",
            "-n",
            "0",
        ),
    ),
    "generated_dependency_map": EXAMPLE_COMMANDS["automated.generated-dependency-map"],
    "generated_reference": EXAMPLE_COMMANDS["automated.generated-reference"],
    "skill_semantic_contract": (("uv", "run", "python", "-m", "scripts.check_skill_documentation_contract", "--json"),),
    "source_contract": (("uv", "run", "python", "scripts/check_documentation_contract.py"),),
}

OWNER_PHASES: dict[str, Literal["leaf", "contributor_journey"]] = {
    **dict.fromkeys((*EXAMPLE_COMMANDS, *DOCUMENT_COMMANDS), "leaf"),
    "automated.contributor-journey": "contributor_journey",
    "contributor_gate": "contributor_journey",
    "live_cutover": "leaf",
    "policy_validator": "leaf",
}


@dataclass(frozen=True, kw_only=True)
class TranscriptAssertion:
    """Legacy transcript expectation, never an approved behavioral verifier."""

    stream: Literal["stdout", "stderr"]
    contains: str


@dataclass(frozen=True, kw_only=True)
class OuterScenario:
    """Fixed outer journey identity with behavioral verification still pending."""

    identifier: str
    actor: Literal["external_contributor", "external_user"]
    argv: tuple[str, ...]
    assertions: tuple[TranscriptAssertion, ...]
    precondition_id: str
    behavioral_verifier: None = None


OUTER_SCENARIOS: tuple[OuterScenario, ...] = (
    OuterScenario(
        identifier="external-contributor-bootstrap",
        actor="external_contributor",
        argv=("make", "bootstrap"),
        assertions=(TranscriptAssertion(stream="stdout", contains="pre-commit"),),
        precondition_id="fresh-fork-contributor-checkout",
    ),
    OuterScenario(
        identifier="external-contributor-changelog",
        actor="external_contributor",
        argv=("uv", "run", "python", "scripts/check_changelog_fragment.py"),
        assertions=(TranscriptAssertion(stream="stdout", contains="PASS"),),
        precondition_id="contributor-change-with-changelog-fragment",
    ),
    OuterScenario(
        identifier="external-contributor-docs-only",
        actor="external_contributor",
        argv=("git", "diff", "--check"),
        assertions=(),
        precondition_id="contributor-documentation-only-change",
    ),
    OuterScenario(
        identifier="external-contributor-fork-ci",
        actor="external_contributor",
        argv=("gh", "pr", "checks", "--watch"),
        assertions=(TranscriptAssertion(stream="stdout", contains="pass"),),
        precondition_id="external-fork-pull-request",
    ),
    OuterScenario(
        identifier="external-contributor-hooks",
        actor="external_contributor",
        argv=("pre-commit", "run", "--all-files"),
        assertions=(TranscriptAssertion(stream="stdout", contains="Passed"),),
        precondition_id="contributor-checkout-with-installed-hooks",
    ),
    OuterScenario(
        identifier="external-contributor-python-tests",
        actor="external_contributor",
        argv=("uv", "run", "pytest", "tests/", "-q", "-n", "4"),
        assertions=(TranscriptAssertion(stream="stdout", contains="passed"),),
        precondition_id="contributor-python-source-change",
    ),
    OuterScenario(
        identifier="external-user-offline-base",
        actor="external_user",
        argv=("fieldkit", "doctor", "--json"),
        assertions=(TranscriptAssertion(stream="stdout", contains='"configuration_state"'),),
        precondition_id="isolated-base-install-without-integration-credentials",
    ),
    OuterScenario(
        identifier="external-user-recovery-isolation",
        actor="external_user",
        argv=("python", "-m", "pip", "uninstall", "-y", "fieldkit-cli"),
        assertions=(TranscriptAssertion(stream="stdout", contains="Successfully uninstalled"),),
        precondition_id="isolated-installed-candidate-with-retained-workspace",
    ),
    OuterScenario(
        identifier="external-user-sdist-install",
        actor="external_user",
        argv=("python", "-m", "pip", "install", "fieldkit_cli-1.0.0.tar.gz"),
        assertions=(TranscriptAssertion(stream="stdout", contains="Successfully installed"),),
        precondition_id="fresh-environment-with-exact-retained-sdist",
    ),
    OuterScenario(
        identifier="external-user-wheel-install",
        actor="external_user",
        argv=("python", "-m", "pip", "install", "fieldkit_cli-1.0.0-py3-none-any.whl"),
        assertions=(TranscriptAssertion(stream="stdout", contains="Successfully installed"),),
        precondition_id="fresh-environment-with-exact-retained-wheel",
    ),
)
