"""In-process Click introspection registry — the machine-readable CLI surface.

Walks the `_COMMANDS` dispatch table (`fieldkit.__main__`), lazily importing
each top-level group and recursively descending into its subcommands, to build
a flat list of every leaf command's name, summary, arguments, flags, write
classification, and account-scope support.

This is the walker referenced by D4 in
`openspec/changes/cli-ux-redesign/design.md`: "Generated by the same
in-process Click introspection that the generate_cli_docs.py rewrite uses ...
one mechanism, two consumers." `fieldkit commands --json`
(`fieldkit.commands.commands.cli`) is the first consumer. The planned
in-process rewrite of `scripts/generate_cli_docs.py` (implementation change) is tracked
separately and is expected to become the second — not done here, to keep this
change scoped to the Wave 5 registry task.

`write_class` has two possible provenances, and `write_class_source` says
which one produced it:

- **declared** — the command carries `@declare_write(...)`. This is a
  statement about what the command *touches*, independent of its flag
  surface, and it is the only form safe to gate on.
- **inferred** — no declaration, so it falls back to flag presence (D3 in the
  same design doc): `--confirm` → "external", `--dry-run` → "workspace",
  neither → "read-only". This describes which flags a command *offers*.

The distinction is not pedantry. Inference cannot detect the failure it most
needs to: a command that writes externally *without* exposing `--confirm`
infers as "read-only", so a check of the form "external writes must have
`--confirm`" reduces to `X and not X` and cannot fail for any flag
combination. The `issue` subcommands — which POST to the GitHub REST API
(`commands/issue/gh_store.py`) — were the live instance of exactly that.
`scripts/check_flag_contract.py` therefore gates on declarations only, and
reports inferred entries separately as unverified.

Account-scope remains a pure flag observation (`--account` present), which is
sound: it is a claim about the flag surface, which is what it reads.
"""

import importlib
import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass, field
from typing import Any, Literal, TypeVar, cast

import click

from fieldkit.config.optional_dependencies import SKIP_OPTIONAL_PROFILE_CHECKS_META_KEY

_EXIT_CODES_RE = re.compile(r"Exit codes:.*?(?=\n\s*\n|\Z)", re.DOTALL)

WriteClass = Literal["read-only", "workspace", "external"]

#: What a command's `--account` option means. These are not interchangeable, and
#: a single "has --account" boolean cannot tell them apart:
#:
#: - "filter"   — optional; the command spans every account by default and this
#:                narrows it. `pursuit audit --account acme`.
#: - "selector" — names the single account the command acts on. Omitting it does
#:                not widen the command, it just leaves the target unspecified.
#:                `pursuit create --account acme` decides where the file is written.
#:
#: An agent that reads "supports --account" and infers "I can narrow this" would
#: be wrong about the three `pursuit` commands where the flag is mandatory.
AccountScope = Literal["filter", "selector"]

#: Attribute the declaration is stashed under on the `click.Command` object.
#: Name-mangled deliberately: nothing outside this module should read it directly.
_DECLARATION_ATTR = "__fieldkit_write_declaration__"

#: Attribute holding an explicit `AccountScope`, for the cases requiredness gets wrong.
_ACCOUNT_SCOPE_ATTR = "__fieldkit_account_scope__"

_C = TypeVar("_C", bound=click.Command)


@dataclass(frozen=True)
class CommandArgument:
    """A positional argument of a leaf command."""

    name: str
    required: bool
    type_name: str

    def to_dict(self) -> dict[str, Any]:
        return {"name": self.name, "required": self.required, "type": self.type_name}


@dataclass(frozen=True)
class CommandFlag:
    """An option (flag) of a leaf command."""

    opts: list[str]
    is_flag: bool
    type_name: str
    help: str | None

    def to_dict(self) -> dict[str, Any]:
        return {"opts": self.opts, "is_flag": self.is_flag, "type": self.type_name, "help": self.help}


@dataclass(frozen=True)
class WriteDeclaration:
    """A command's author-declared statement of what it writes.

    Independent of the command's flag surface — that independence is the whole
    point. `write_class` inferred from `--confirm`/`--dry-run` cannot catch a
    command that writes externally without offering the flag, because the
    inference and the check would read the same bit.

    `confirm_exempt`, when set, records *why* an external-write command does
    not prompt (typically: it is invoked unattended by the driver loop, so an
    interactive confirmation would deadlock it). The exemption is reported by
    `scripts/check_flag_contract.py` rather than silently skipped — an
    exemption you can grep for is the difference between a considered decision
    and an invisible hole.
    """

    write_class: WriteClass
    confirm_exempt: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {"write_class": self.write_class, "confirm_exempt": self.confirm_exempt}


def declare_write(write_class: WriteClass, *, confirm_exempt: str | None = None) -> Callable[[_C], _C]:
    """Declare what a leaf command writes, independently of its flag surface.

    Apply *above* the Click command decorator, so it receives the built
    `click.Command` rather than the undecorated function::

        @declare_write("external", confirm_exempt="driver loop invokes this unattended")
        @cli.command("create")
        @click.option("--title", required=True)
        def create_cmd(title: str) -> None:
            ...

    Commands with no declaration fall back to flag inference and are reported
    with `write_class_source="inferred"`, so consumers can tell a stated fact
    from a guess.

    Raises:
        TypeError: if applied below the Click decorator, where it would
            silently annotate a plain function and be invisible to the
            registry.
        ValueError: if `confirm_exempt` is set on a non-external declaration,
            where it would have no meaning.
    """
    if confirm_exempt is not None and write_class != "external":
        raise ValueError(f"confirm_exempt is only meaningful for external writes, not {write_class!r}")

    declaration = WriteDeclaration(write_class=write_class, confirm_exempt=confirm_exempt)

    def decorator(cmd: _C) -> _C:
        if not isinstance(cmd, click.Command):
            raise TypeError(
                f"@declare_write must be applied above the Click command decorator; "
                f"got {type(cmd).__name__}. Move it to the top of the decorator stack."
            )
        setattr(cmd, _DECLARATION_ATTR, declaration)
        return cmd

    return decorator


def declare_account_scope(scope: AccountScope) -> Callable[[_C], _C]:
    """Declare what a command's `--account` option means, when requiredness misleads.

    A required `--account` is a selector and an optional one is a filter — true
    for 26 of the 27 commands that have the flag, so it is inferred rather than
    declared. `pursuit advance` is the exception: its `--account` is optional
    only because there is a positional `PURSUIT_SPEC` alternative, and it names
    the pursuit to advance rather than narrowing a sweep.

    Apply above the Click command decorator, as with `declare_write`.
    """

    def decorator(cmd: _C) -> _C:
        if not isinstance(cmd, click.Command):
            raise TypeError(
                f"@declare_account_scope must be applied above the Click command decorator; got {type(cmd).__name__}."
            )
        setattr(cmd, _ACCOUNT_SCOPE_ATTR, scope)
        return cmd

    return decorator


def _account_scope(cmd: click.Command) -> AccountScope | None:
    """Classify the command's `--account` option, or None if it has none."""
    option = next(
        (p for p in cmd.params if isinstance(p, click.Option) and "--account" in p.opts),
        None,
    )
    if option is None:
        return None
    declared = getattr(cmd, _ACCOUNT_SCOPE_ATTR, None)
    if isinstance(declared, str) and declared in ("filter", "selector"):
        return cast(AccountScope, declared)
    return "selector" if option.required else "filter"


@dataclass(frozen=True)
class CommandEntry:
    """One leaf command's full registry record."""

    full_name: str
    summary: str
    arguments: list[CommandArgument] = field(default_factory=list)
    flags: list[CommandFlag] = field(default_factory=list)
    write_class: str = "read-only"
    account_scopable: bool = False
    exit_code_notes: str | None = None
    write_class_source: Literal["declared", "inferred"] = "inferred"
    confirm_exempt: str | None = None
    account_scope: AccountScope | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "full_name": self.full_name,
            "summary": self.summary,
            "arguments": [a.to_dict() for a in self.arguments],
            "flags": [f.to_dict() for f in self.flags],
            "write_class": self.write_class,
            "write_class_source": self.write_class_source,
            "confirm_exempt": self.confirm_exempt,
            "account_scopable": self.account_scopable,
            "account_scope": self.account_scope,
            "exit_code_notes": self.exit_code_notes,
        }


def _parse_exit_code_notes(help_text: str | None) -> str | None:
    """Extract the "Exit codes: ..." paragraph from a docstring, if present."""
    if not help_text:
        return None
    match = _EXIT_CODES_RE.search(help_text)
    if not match:
        return None
    lines = [line.strip() for line in match.group(0).splitlines() if line.strip()]
    return " ".join(lines)


def _classify_write(flag_names: set[str]) -> str:
    """Heuristic write classification per D3.3 — confirm beats dry-run beats read-only.

    Fallback for undeclared commands only. Describes the flag surface, not the
    behaviour: see `declare_write` for the signal that is safe to gate on.
    """
    if "--confirm" in flag_names:
        return "external"
    if "--dry-run" in flag_names:
        return "workspace"
    return "read-only"


def get_write_declaration(cmd: click.Command) -> WriteDeclaration | None:
    """Return the command's `@declare_write` declaration, or None if undeclared."""
    declaration = getattr(cmd, _DECLARATION_ATTR, None)
    return declaration if isinstance(declaration, WriteDeclaration) else None


def _leaf_entry(cmd: click.Command, full_name: str) -> CommandEntry:
    arguments = [
        CommandArgument(name=p.name or "", required=bool(p.required), type_name=p.type.name)
        for p in cmd.params
        if isinstance(p, click.Argument)
    ]
    flags = [
        CommandFlag(opts=list(p.opts), is_flag=bool(p.is_flag), type_name=p.type.name, help=p.help)
        for p in cmd.params
        if isinstance(p, click.Option) and p.name != "help"
    ]
    flag_names = {opt for f in flags for opt in f.opts}

    declaration = get_write_declaration(cmd)

    return CommandEntry(
        full_name=full_name,
        summary=cmd.get_short_help_str(limit=200),
        arguments=arguments,
        flags=flags,
        write_class=declaration.write_class if declaration else _classify_write(flag_names),
        write_class_source="declared" if declaration else "inferred",
        confirm_exempt=declaration.confirm_exempt if declaration else None,
        account_scopable="--account" in flag_names,
        account_scope=_account_scope(cmd),
        exit_code_notes=_parse_exit_code_notes(cmd.help),
    )


@dataclass(frozen=True)
class CommandNode:
    """One node of the CLI tree — a group or a leaf — with its rendering context.

    The unit of the shared traversal. `build_registry` keeps the leaves;
    `scripts/generate_cli_docs.py` renders help for every node. Both read the
    same walk, which is what D4's "one mechanism, two consumers" asks for: a
    second traversal would drift from this one silently, and the drift would
    surface as documentation that disagrees with the registry.
    """

    command: click.Command
    full_name: str
    ctx: click.Context
    depth: int
    is_leaf: bool


def _child_context(cmd: click.Command, info_name: str, parent: click.Context | None) -> click.Context:
    """Build a Context that honours the command's own `context_settings`.

    `click.Context(cmd, ...)` on its own ignores `context_settings`, which is
    where `max_content_width` lives — so help rendered through a bare Context
    wraps at a different width than the same command's real `--help`. Click's
    own `make_context()` applies them, but it also parses argv and can invoke
    callbacks or raise `UsageError`; for pure introspection that is a liability.
    Passing the settings through explicitly gets the formatting without the
    parsing, because every `context_settings` key is a `Context.__init__` kwarg
    (that is exactly how `make_context` forwards them).
    """
    return click.Context(cmd, info_name=info_name, parent=parent, **cmd.context_settings)


def _walk_command(cmd: click.Command, full_name: str, ctx: click.Context, depth: int) -> list[CommandNode]:
    if isinstance(cmd, click.Group):
        sub_names = sorted(cmd.list_commands(ctx))
        if not sub_names:
            # A group with zero registered subcommands (e.g. `completion`,
            # which only uses invoke_without_command=True to dispatch on a
            # positional argument) behaves like a leaf command — treat it
            # as one rather than silently dropping it from the registry.
            return [CommandNode(command=cmd, full_name=full_name, ctx=ctx, depth=depth, is_leaf=True)]
        nodes = [CommandNode(command=cmd, full_name=full_name, ctx=ctx, depth=depth, is_leaf=False)]
        for sub_name in sub_names:
            sub_cmd = cmd.get_command(ctx, sub_name)
            if sub_cmd is None:
                continue
            sub_ctx = _child_context(sub_cmd, sub_name, ctx)
            nodes.extend(_walk_command(sub_cmd, f"{full_name} {sub_name}", sub_ctx, depth + 1))
        return nodes
    return [CommandNode(command=cmd, full_name=full_name, ctx=ctx, depth=depth, is_leaf=True)]


def walk_cli(group_names: Sequence[str] | None = None) -> list[CommandNode]:
    """Walk the CLI tree from `_COMMANDS`, returning every group and leaf node.

    Args:
        group_names: Top-level groups to walk, in the order given. Defaults to
            every group in `_COMMANDS`, alphabetically. The docs generator
            passes its own display order; the registry takes the default.

    `_COMMANDS` is imported lazily inside the body (rather than at module
    level) to avoid a hard import-time dependency between this module and
    `fieldkit.__main__` — mirroring the lazy-import pattern `_LazyGroup` itself
    uses for the same dispatch table.
    """
    from fieldkit.__main__ import _COMMANDS
    from fieldkit.__main__ import cli as root_cli

    names = sorted(_COMMANDS) if group_names is None else [g for g in group_names if g in _COMMANDS]

    # Top-level groups hang off a real `fieldkit` root context. Without it a
    # group's rendered usage line reads "Usage: auth [OPTIONS]" rather than
    # "Usage: fieldkit auth [OPTIONS]", because Click derives `command_path`
    # by walking parent contexts.
    root_ctx = _child_context(root_cli, "fieldkit", None)
    root_ctx.meta[SKIP_OPTIONAL_PROFILE_CHECKS_META_KEY] = True

    nodes: list[CommandNode] = []
    for group_name in names:
        _description, module_path = _COMMANDS[group_name]
        module = importlib.import_module(module_path)
        group_cmd: click.Command = module.cli
        ctx = _child_context(group_cmd, group_name, root_ctx)
        nodes.extend(_walk_command(group_cmd, group_name, ctx, depth=0))
    return nodes


def build_registry() -> list[CommandEntry]:
    """Return the flat leaf registry — every leaf command in the CLI tree."""
    return [_leaf_entry(node.command, node.full_name) for node in walk_cli() if node.is_leaf]
